AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.7
    Timeout: 60
    Environment:
      Variables:
        # Set localtest env
        TEST_ENV: LOCAL_TEST
        # Set environment variable so amazon service can be switched in local settings
        # This has to be matched with localstack config in docker-compose.yaml
        # Current example contains DynamoDB and S3
        ANNOTATION_TABLE: ANNOTATION_TABLE
        LOCAL_DYNAMODB: http://localstack:4569
        BUCKET_NAME: VARSAP_BUCKET
        LOCAL_S3_ENDPOINT: http://localstack:4572
        ANNOTATION_QUEUE: ANNOTATION_QUEUE
        LOCAL_SQS_ENDPOINT: http://localstack:4576
        LOG_LEVEL: DEBUG

Resources:
  RequestAnnotation:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: annotation_requestor.insert_annotation

  HandleS3Event:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: s3_event_handler.trigger_annotation

  AnnotaionDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ANNOTATION_TABLE
      PrimaryKey:
        Name: job_id
        Type: String
      AttributeDefinitions:
        AttributeName: job_id
        AttributeType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
